# Direct output from ROS
image_width: 1280
image_height: 720
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [ 781.72069,    0.     ,  661.42903,
            0.     ,  780.33569,  364.6039 ,
            0.     ,    0.     ,    1.     ]
camera_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.311177, 0.086914, 0.001869, -0.000153, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [ 1.,  0.,  0.,
          0.,  1.,  0.,
          0.,  0.,  1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [ 590.32654,    0.     ,  671.50104,    0.     ,
            0.     ,  724.16986,  366.63294,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]
